# Generated by Django 5.0.3 on 2024-03-21 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=128, unique=True)),
                ('lastName', models.CharField(max_length=128)),
                ('numberOfCats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=128)),
                ('studentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.student')),
            ],
        ),
    ]
